// <auto-generated />
using System;
using GolfAssociationCommunity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfAssociationCommunity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624225005_AddHeroOverlayOpacity")]
    partial class AddHeroOverlayOpacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GolfAssociationCommunity.Models.AdminAuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AtUtc");

                    b.ToTable("AdminAuditEvents");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationCharity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.ToTable("AssociationCharities");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPlay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.ToTable("AssociationMedia");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.ToTable("AssociationOfficers");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HandicapIndex")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId", "Email");

                    b.ToTable("AssociationPlayers");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationSponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.ToTable("AssociationSponsors");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.GolfAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizeNetApiLoginId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizeNetTransactionKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AuthorizeNetUseSandbox")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharityDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharityUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroOverlayOpacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroVideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GolfAssociations");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Leaderboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssociationPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flight")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreDifferential")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociationPlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Leaderboards");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.PlayerScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssociationPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HandicapStrokes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolePar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TiebreakerHoleHandicap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociationPlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("PlayerScores");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssociationPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizeNetTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLast4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flight")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Handicap")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesPracticeRound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PaymentConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegistrationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TournamentFlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WithdrawalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WithdrawalReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociationPlayerId");

                    b.HasIndex("TournamentFlightId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.SponsorshipPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId", "DisplayOrder");

                    b.ToTable("SponsorshipPackages");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.SponsorshipPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizeNetTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLast4")
                        .HasColumnType("TEXT");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PaymentConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SponsorCompany")
                        .HasColumnType("TEXT");

                    b.Property<string>("SponsorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SponsorshipPackageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.HasIndex("PaidAtUtc");

                    b.HasIndex("SponsorshipPackageId");

                    b.ToTable("SponsorshipPayments");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfAssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GolfCourse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPracticeRound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PracticeRoundFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GolfAssociationId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.TournamentFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentFlights");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.ApplicationUser", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("Members")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationCharity", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("Charities")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationMedia", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("MediaItems")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationOfficer", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("OfficersAndMembers")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationPlayer", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("Players")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationSponsor", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("Sponsors")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Leaderboard", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.AssociationPlayer", "AssociationPlayer")
                        .WithMany("LeaderboardEntries")
                        .HasForeignKey("AssociationPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfAssociationCommunity.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationPlayer");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.PlayerScore", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.AssociationPlayer", "AssociationPlayer")
                        .WithMany("Scores")
                        .HasForeignKey("AssociationPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfAssociationCommunity.Models.Tournament", "Tournament")
                        .WithMany("PlayerScores")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationPlayer");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Registration", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.AssociationPlayer", "AssociationPlayer")
                        .WithMany("Registrations")
                        .HasForeignKey("AssociationPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfAssociationCommunity.Models.TournamentFlight", "TournamentFlight")
                        .WithMany()
                        .HasForeignKey("TournamentFlightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfAssociationCommunity.Models.Tournament", "Tournament")
                        .WithMany("Registrations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationPlayer");

                    b.Navigation("Tournament");

                    b.Navigation("TournamentFlight");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.SponsorshipPackage", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("SponsorshipPackages")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.SponsorshipPayment", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("SponsorshipPayments")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfAssociationCommunity.Models.SponsorshipPackage", "SponsorshipPackage")
                        .WithMany("SponsorshipPayments")
                        .HasForeignKey("SponsorshipPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GolfAssociation");

                    b.Navigation("SponsorshipPackage");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Tournament", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.GolfAssociation", "GolfAssociation")
                        .WithMany("Tournaments")
                        .HasForeignKey("GolfAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfAssociation");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.TournamentFlight", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.Tournament", "Tournament")
                        .WithMany("Flights")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfAssociationCommunity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GolfAssociationCommunity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.AssociationPlayer", b =>
                {
                    b.Navigation("LeaderboardEntries");

                    b.Navigation("Registrations");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.GolfAssociation", b =>
                {
                    b.Navigation("Charities");

                    b.Navigation("MediaItems");

                    b.Navigation("Members");

                    b.Navigation("OfficersAndMembers");

                    b.Navigation("Players");

                    b.Navigation("Sponsors");

                    b.Navigation("SponsorshipPackages");

                    b.Navigation("SponsorshipPayments");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.SponsorshipPackage", b =>
                {
                    b.Navigation("SponsorshipPayments");
                });

            modelBuilder.Entity("GolfAssociationCommunity.Models.Tournament", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("PlayerScores");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
