// <auto-generated />
using GolfAssociationCommunity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GolfAssociationCommunity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624000001_RemoveStableford")]
    partial class RemoveStableford
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal stub — model snapshot in ApplicationDbContextModelSnapshot.cs
        }
    }
}
